Modules/Vendor/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;



   


Route::middleware('auth')->prefix('vendor')->group(function() {
   
    Route::resource('vendor-user', 'VendorUserController')->middleware('hq');
    Route::resource('vendortype', 'VendorTypeController')->middleware('hq');
    Route::resource('vendorgroup', 'VendorGroupController')->middleware('hq');
    Route::resource('vendors', 'VendorController')->middleware('hq');
    Route::resource('profile', 'ProfileController')->middleware('vendor');
    Route::resource('dashboard', 'DashboardController')->middleware('vendor');
    Route::resource('sellrequest', 'SellRequestController')->middleware('vendor');
    Route::resource('vendor-invoice', 'SellRequestController')->middleware('vendor');
   
   
    
    Route::get('/sell-request/edit/{id}','SellRequestController@sellRequestEdit')->name('sell.request.edit')->middleware('vendor');
    Route::get('/sell-request/details/{id}','SellRequestController@sellRequestDetails')->name('sell.request.details')->middleware('vendor');
    Route::post('/sell-request/update/{id}','SellRequestController@sell_request_update')->name('sell.request.update')->middleware('vendor');
    Route::get('/sell-request-status/','SellRequestController@sell_request_status_remove')->name('sell.request.remove')->middleware('vendor');
    Route::get('/sell-remain', 'SellRequestController@sellRemainRequest')->name('sell.request.remain')->middleware('vendor');
    Route::get('/sell-remain-details/{id}', 'SellRequestController@sellRemainDetailRequest')->name('sell.remain.details')->middleware('vendor');
    Route::get('/sell-remain-edit/{id}', 'SellRequestController@sellRemainEditRequest')->name('sell.remain.edit')->middleware('vendor');
    Route::get('invoices', 'InvoiceController@invoice')->name('invoice')->middleware('vendor');
    Route::post('vendor-filter','VendorController@vendor_details')->name('filter.vendor')->middleware('hq');
    Route::get('vendor-list','VendorController@get_all_vendor')->name('vendor.list')->middleware('hq');
    Route::get('get-product-by-type-id','VendorController@getProductByTypeId')->name('product.get.by.type.id');
    Route::get('vendor-profile/{id}', 'VendorProfileController@show')->middleware('hq');
    Route::get('vendor-details/{id}','VendorProfileController@vendor_details')->name('vendor.details')->middleware('hq');
    Route::get('/vendor-purchase-order/{id}','VendorProfileController@vendor_purchase_orders')->name('vendor.purchase.order')->middleware('vendor');
    Route::get('/vendor-purchase-product/{id}','VendorProfileController@vendor_purchase_product')->name('vendor.purchase.product')->middleware('vendor');
    Route::get('/vendor-purchase-payment/{id}','VendorProfileController@vendor_purchase_payment')->name('vendor.purchase.payment')->middleware('vendor');
    Route::get('/vendortype-edit/{id}', 'VendorTypeController@vendor_type_edit')->middleware('hq');
    Route::post('/vendortype-update', 'VendorTypeController@vednorUpdate')->middleware('hq');
    Route::get('/vendorgroup-edit/{id}', 'VendorGroupController@vendor_group_edit')->middleware('hq');
    Route::post('/vendorgroup-update', 'VendorGroupController@vendorUpdate')->middleware('hq');
   
   
    
});

Modules/Vendor/Http/Controllers/InvoiceController.php
<?php

namespace Modules\Vendor\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Procurement\Entities\PurchaseOrder;
use Modules\Vendor\Entities\VendorUser;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
       // return view('vendor::vendor-management.invoice.index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('vendor::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show(Request $id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('vendor::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }


    public function invoice()
    {

        //$invoice = PurchaseOrder::with(['purchase_order_details','vendor', 'purchase_order_details.product', 'purchase_order_details.unit','purchase_order_details.uom'])->first();

        $vendor = VendorUser::where('user_id',auth()->user()->id)->first();
        if (auth()->user()->role == 'admin' || auth()->user()->role == 'developer') {
            $sell_request_list = PurchaseOrder::with(['hq_requisition', 'vendor', 'purchase_order_details'])
                ->orderBy('id', 'DESC')
                ->get();

        } else {
            $sell_request_list = PurchaseOrder::with(['hq_requisition', 'vendor', 'purchase_order_details'])
                ->where('vendor_id',$vendor->vendor_id)
                ->orderBy('id', 'DESC')
                ->get();
        }

        return view('vendor::vendor-management.invoice.index', compact('sell_request_list'));
    }
}

Modules/Vendor/Resources/views/vendor-management/invoice/index.blade.php
@extends('dboard.index')

@section('title','Sell Request Details')

@section('dboard_content')
    @push('style')
        <link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
    @endpush
    <div class="row">
        <div class="col-md-12">
            <div class="tile mb-1">
                <div class="tile-body">

                    <div class="row align-items-center">
                        <div class="col-md-9 text-left">
                            <h2 class="title-heading"> Invoice List <span class="text-primary"></span></h2>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 ">
            {{--<ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('vendor/sellrequest') ? 'active' : '' }} " aria-current="page"
                       href="{{route('sellrequest.index')}}">
                        <h4 class="title-heading">Sell Request List </h4>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ request()->is('vendor/sell-remain') ? 'active' : '' }} "
                       href="{{route('sell.request.remain')}}"><h4>Remain List</h4></a>
                </li>
            </ul>--}}
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive bg-light p-3 ">
                        <table class="table table-bordered table-striped table-hover requisition-list" id="requisitionList">
                            <thead>
                            <tr>
                                <th>Details</th>
                                <th>Priority</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(!empty($sell_request_list))
                                @foreach($sell_request_list as $key=>$sellRequest)
                                    <tr>
                                        <td>
                                            <address>
                                                <strong>Vendor: {{$sellRequest->vendor->name}} </strong><br>
                                                <strong>Purchase_No:{{$sellRequest->purchase_order_no}}</strong><br>
                                                Created Date: {{$sellRequest->purchase_order_date}} <br>
                                                Request Delivery Date: {{$sellRequest->requested_delivery_date}}<br>
                                            </address>
                                        </td>
                                        @if($sellRequest->priority == 1)
                                            <td><strong">High</strong></td>
                                        @elseif($sellRequest->priority == 2)
                                            <td><strong>Low</strong></td>
                                        @endif


                                        <td>

                                            @if($sellRequest->status == 'Pending')
                                                <p>Pending</p>

                                            @elseif($sellRequest->status == 'Approved')
                                                <p>Approved</p>
                                            @elseif(isset($sellRequest->purchase_order_details[0]) && $sellRequest->purchase_order_details[0]->order_quantity !== $sellRequest->purchase_order_details[0]->delivered_quantity)
                                                <p>Partial</p>
                                            @endif
                                        </td>

                                        <td>
                                            <a href="{{route('sell.request.details',$sellRequest->id)}}"
                                               class="btn details-btn" type="button"><i class="fa fa-eye"
                                                                                        aria-hidden="true"
                                                                                        data-toggle="tooltip"
                                                                                        title="Details"> </i></a>

                                        </td>

                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div><!-- end .col-md-12 -->
            </div><!-- end .row -->
        </div> <!-- end .col-md-12 -->
    </div><!-- end .row -->

@endsection
@push('post_scripts')
    <script type="text/javascript" src="{{asset('js/plugins/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/plugins/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#requisitionList').DataTable();
        });
    </script>
@endpush