Modules/Inventory/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::middleware('auth')->prefix('inventory')->group(function() {

    Route::get('/dashboard', 'DashboardController@index')->name('inventory.dashboard');

    Route::resource('/warehouse-user', 'WarehouseUserController');
    Route::resource('/warehouse-type', 'WarehouseTypeController')->middleware('hub');
    Route::get('/', 'InventoryController@index');
    Route::resource('/warehouse', 'WarehouseController')->middleware('warhouseOrHub');
    Route::resource('inventory-location','InventoryLocationController')->middleware('warhouseOrHub');

    Route::get('/g-store', 'InventoryLocationController@get_store')->name('g_store');

    Route::resource('inventory-GRN','InventoryGRNController')->middleware('warehouse');
    Route::get('grnProcess/{purchase_order_id}/{product_id}','InventoryGRNController@grnProcess')->name('grn.process');
    Route::post('batch-process','InventoryGRNController@process_batch_no')->name('batch.process');


    Route::get('hub-stocks/list','HubStockEntryController@index')->name('hubStockEntry.list')->middleware('warehouse');
    Route::get('hub-stocks/create/{id}','HubStockEntryController@hubStockEntryCreate')->name('hubStockEntry.create');
    Route::post('hub-stocks/store','HubStockEntryController@hubStockEntryStore')->name('hubStockEntry.store')->middleware('warehouse');
    Route::get('available-stock','HubStockEntryController@availableStock')->name('hubStockEntry.availablestock')->middleware('warhouseOrHub');
    Route::get('available-stock-details/{id}','HubStockEntryController@availableStockDetails')->name('hubStockEntry.availablestock.details')->middleware('warhouseOrHub');
    //Start Store Stock Entry//
    Route::get('store-stocks/list','StoreStockEntryController@index')->name('storeStockEntry.list')->middleware('store');
    Route::get('store-stocks/create/{id}','StoreStockEntryController@storeStockEntryCreate')->name('storeStockEntry.create');
    Route::post('store-stocks/store','StoreStockEntryController@storeStockEntryStore')->name('storeStockEntry.store')->middleware('store');
    // End Store Stock Entry//



    Route::resource('requisition', 'RequisitionController')->middleware('warehouse');
    Route::get('/requisitionlist', 'RequisitionController@requisition_list')->name('requisitionlist');
    //Route::get('/panding-details', 'RequisitionController')->name('panding.details');
    Route::get('/pen-process/{id}', 'RequisitionController@process')->name('process');

    //Purchase Distribute
    Route::get('/purchase-distribution', 'Distribution\PurchaseDistributeController@purchase_distribution')->name('purchase.distribution');
    Route::get('/purchase-distribution-show/{id}', 'Distribution\PurchaseDistributeController@purchase_distribution_show')->name('purchase.distribution.show');
    Route::get('/purchase-distribution-process', 'Distribution\PurchaseDistributeController@purchase_distribution_process')->name('purchase.distribution.process');

    //Regular Distribute
    Route::get('/distribution-process', 'Distribution\RegularDistributeController@distribution_process')->name('distribution.process');
    Route::get('/distribution-process-show/{id}', 'Distribution\RegularDistributeController@distribution_process_show')->name('distribution.process.show');
    Route::get('/distribution-process-process/{id}', 'Distribution\RegularDistributeController@distribution_process_process')->name('distribution.process.process');
    Route::post('/distribution-process-store', 'Distribution\RegularDistributeController@distribution_process_store')->name('distribution.process.store');

    //Hold Distribute
    Route::get('/hold-distribution', 'Distribution\HoldDistributeController@hold_distribution')->name('hold.distribution');
    Route::get('/hold-distribution-details/{id}', 'Distribution\HoldDistributeController@hold_distribution_details')->name('hold.distribution.details');
    Route::get('/hold-distribution-process/{id}', 'Distribution\HoldDistributeController@hold_distribution_process')->name('hold.distribution.process');
    Route::post('/distribute-hold-requisition','Distribution\HoldDistributeController@distribute_hold_quantity')->name('distribute.hold.quantity');

    //Barcode for warehouse
    Route::resource('barcode', 'BarcodeController')->middleware('warehouse');
    Route::get('barcode/{grn_id}/generate/{stock_id}','BarcodeController@generate')->name('barcode.generate')->middleware('warehouse');

    //Barcode for store
    Route::get('store-barcode', 'StoreBarcodeController@index')->name('store-barcode')->middleware('store');
    Route::get('store-barcode/{entry_id}/show/{batch}/product/{product_id}', 'StoreBarcodeController@show_store_product')->name('store-barcode.show.product')->middleware('store');
    Route::post('store-barcode/{entry_id}/generate/{product_id}', 'StoreBarcodeController@generate_barcode')->name('store-barcode.generate')->middleware('store');

    Route::get('/independent-stock','IndependentStockController@index')->name('independent.stock');
    Route::post('/store-independent-stock','IndependentStockController@store')->name('store.independent.stock');

    Route::get('/stock-alert-lists', 'StockAlertController@index')->name('compare.stock.alert');
    Route::get('/return-products','WarehouseReturnProductController@index')->name('warehouse.return.products');
    Route::get('/damage-products','WarehouseDamageProductController@index')->name('warehouse.damage.products');
});

Modules/Inventory/Entities/WarehouseUser.php
<?php

namespace Modules\Inventory\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class WarehouseUser extends Model
{
    use HasFactory;

    protected $table = 'warehouse_user';
    protected $fillable = ['warehouse_id','user_id','status'];
    
    
}

Modules/Inventory/Http/Controllers/WarehouseUserController.php
<?php

namespace Modules\Inventory\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Inventory\Repositories\WarehouseUserInterface;

class WarehouseUserController extends Controller
{

    private $warehouse_user;
    public function __construct(WarehouseUserInterface $warehouse_user){
        $this->warehouse_user = $warehouse_user;
    }
    
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
       $all_warehouse_user=  $this->warehouse_user->index();
       return view('inventory::inventory-management.warehouse-user.index',compact('all_warehouse_user'));
       
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        $users_and_warehouses = $this->warehouse_user->create();
        return view('inventory::inventory-management.warehouse-user.create',compact('users_and_warehouses'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
      $this->warehouse_user->store($request);
      return redirect()->route('warehouse-user.index')->with('success','Warehouse User Create Successfully');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        $users_and_warehouses = $this->warehouse_user->edit($id);
        return view('inventory::inventory-management.warehouse-user.edit',compact('users_and_warehouses'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
       $this->warehouse_user->update($request,$id);
       return redirect()->route('warehouse-user.index')->with('success','Warehouse User Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        $this->warehouse_user->destroy($id);
        return redirect()->back()->with('success','Warehouse User Status Change Successfully');
    }
}

Modules/Inventory/Resources/views/inventory-management/warehouse-user/create.blade.php
@extends('dboard.index')

@section('title', 'Create New Warehouse User Form')

@section('dboard_content')
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">

        <!-- title -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="title-heading">Create New warehouse User</h2>
          </div>
          <div class="col-md-6 text-right">
            <a class="btn index-btn" href="{{ route('warehouse-user.index') }}">Back</a>
          </div>
        </div><!-- end.row -->
        <hr>

        <!-- data -->
        <form method="POST" action="{{ route('warehouse-user.store') }}">
          @csrf
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <label for="exampleSelect1">Warehouse</label>
                <select class="form-control " name="warehouse_id">
                  <option selected="true" disabled="disabled">Select Warehouse</option>
                  @foreach ($users_and_warehouses['warehouses'] as $warehouse )
                  <option value="{{$warehouse->id}}">{{$warehouse->name}}</option>
                  @endforeach
                </select>
              </div><!-- end.form-group -->
            </div><!-- col-md-4 -->

            <div class="col-md-4">
              <div class="form-group">
                <label for="exampleSelect1">User</label>
                <select class="form-control " name="user_id">
                  <option selected="true" disabled="disabled">Select User</option>
                  @foreach ($users_and_warehouses['users'] as $user )
                  <option value="{{$user->id}}">{{$user->name}}</option>
                  @endforeach
                </select>
              </div>
            </div><!-- end.col-md-4 -->

            <div class="col-md-4">
              <div class="form-group">
                @include('store::shares.status')
              </div>
            </div><!-- end.col-md-4 -->
          </div><!-- end.row -->
          <hr>

          <div class="row text-right">
            <div class="col-md-12">
              <button class="btn create-btn" type="submit">Submit</button>
            </div>
          </div>
        </form>
      </div><!-- end.tile-body -->
    </div><!-- end.tile -->
  </div><!-- end.col-md-12 -->
</div><!-- end.row -->

@endsection

Modules/Inventory/Resources/views/inventory-management/warehouse-user/edit.blade.php
@extends('dboard.index')

@section('title', 'Create New Warehouse User Form')

@section('dboard_content')
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">

        <!-- title -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="title-heading">Update Warehouse User</h2>
          </div>
          <div class="col-md-6 text-right">
            <a class="btn index-btn" href="{{ route('warehouse-user.index') }}">Back</a>
          </div>
        </div><!-- end.row -->
        <hr>

        <!-- data -->
        <form method="POST" action="{{ route('warehouse-user.update', $users_and_warehouses['warehouse_user']->id) }}">
          @csrf
          @method('PATCH')
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="exampleSelect1">Warehouse <span class="text-danger">*</span></label>
                <select class="form-control" name="warehouse_id">
                  <option selected="true" disabled="disabled">Select Warehouse</option>
                  @foreach ($users_and_warehouses['warehouses'] as $warehouse )
                  <option value="{{$warehouse->id}}" @if ($warehouse->id == $users_and_warehouses['warehouse_user']->warehouse_id) selected @endif >{{$warehouse->name}}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="col-md-6">
              <div class="form-group">
                <label for="exampleSelect1">Select User <span class="text-danger">*</span></label>
                <select class="form-control " name="user_id">
                  <option selected="true" disabled="disabled">Select</option>
                  @foreach ($users_and_warehouses['users'] as $user )
                  <option value="{{$user->id}}" @if ($user->id == $users_and_warehouses['warehouse_user']->user_id) selected @endif >{{$user->name}}</option>
                  @endforeach
                </select>
              </div><!-- form-group -->
            </div><!-- end.col-md-6 -->
          </div><!-- end.row -->
          <hr>

          <div class="row text-right">
            <div class="col-md-12">
              <button class="btn create-btn" type="submit">Update</button>
            </div><!-- end.col-md-12 -->
          </div><!-- end.row -->
        </form>
      </div><!-- end.tile-body -->
    </div><!-- end.tile -->
  </div><!-- end.col-md-12 -->
</div><!-- end.row -->

@endsection

Modules/Inventory/Resources/views/inventory-management/warehouse-user/index.blade.php
@extends('dboard.index')

@section('title','View Vendor User Interface')

@section('dboard_content')

    <div class="row" id="actionModal">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <!-- title -->
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <h2 class="title-heading">Warehouse User Details</h2>
                        </div>

                        <div class="col-md-6 text-right">
                            <a class="btn create-btn" href="{{route('warehouse-user.create')}}">Add New Warehouse User</a>
                        </div>
                    </div><!-- end.row -->
                    <hr>

                    <!-- data -->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered" id="StoreTypeTable">
                                    <thead class="thead">
                                    <tr>
                                        <th>SL</th>
                                        <th>Warehouse Name</th>
                                        <th>User  Name</th>
                                        <th>User  Role</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(isset($all_warehouse_user))
                                        @foreach( $all_warehouse_user as $key => $warehouseUser)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td>{{$warehouseUser->warehouse_name}}</td>
                                                <td>{{$warehouseUser->user_name}}</td>
                                                <td>{{$warehouseUser->user_role}}</td>
                                                <td>{{$warehouseUser->warehouse_user_status == 1 ? 'Active' : 'InActive' }}</td>
                                                <td>
                                                    <div class="d-md-flex justify-content-center align-items-center">
                                                        <form class="mr-3" id="delete_form{{$warehouseUser->id}}" method="POST" action="{{ route('warehouse-user.destroy',$warehouseUser->id) }}" onclick="return confirm('Are you sure?')">@csrf
                                                        <input name="_method" type="hidden" value="DELETE">
                                                        <button class="btn edit-btn" type="submit"><i class="fa fa-refresh"></i></button>
                                                    </form>
                                                  

                                                
                                                    <a class="btn edit-btn " href="{{route('warehouse-user.edit',$warehouseUser->id)}}">
                                                        <i class="fa fa-pencil"></i>
                                                    </a>
                                                    </div>
                                                    
                                               
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                    </tbody>
                                </table>
                            </div><!-- end.table-responsive -->
                        </div><!-- end.col-md-12 -->
                    </div><!-- end.row -->
                    
                </div>
            </div>
        </div>
    </div>
@endsection

@push('post_scripts')
    <script type="text/javascript" src="{{asset('js/plugins/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/plugins/dataTables.bootstrap.min.js')}}"></script>
    <script type="text/javascript">$('#StoreTypeTable').DataTable();</script>
@endpush