Modules/Store/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['auth','hq'])->prefix('store')->group(function() {
    Route::resource('storetype', 'StoreTypeController');
    Route::resource('store', 'StoreController');
    Route::resource('storeconfiguration', 'StoreConfigurationController');
    Route::resource('storeuser', 'StoreUserController');
    Route::get('/get-type', 'StoreConfigurationController@get_type')->name('get_type');
    Route::get('/get-store', 'StoreConfigurationController@get_store')->name('get_store');
    Route::get('/g-type', 'StoreUserController@get_type')->name('g_type');
    Route::get('/store-inventory','StoreInventoryController@store_inventory');
});

Modules/Store/Entities/StoreUser.php
<?php

namespace Modules\Store\Entities;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class StoreUser extends Model
{
    protected $guarded = [];

    public function store()
    {
        return $this->belongsTo(Store::class,'store_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

}

Modules/Store/Http/Controllers/StoreUserController.php
<?php

namespace Modules\Store\Http\Controllers;

use Illuminate\Support\Facades\Gate;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Modules\Inventory\Entities\Warehouse;
use Modules\Store\Entities\Store;
use Modules\Store\Entities\StoreUser;
use Modules\Store\Http\Requests\CreateStoreUserRequest;
use Modules\Store\Http\Requests\UpdateStoreUserRequest;
use Modules\Store\Repositories\StoreUserInterface;
use Modules\Store\Repositories\StoreInterface;
use Modules\User\Repositories\UserRepositoryInterface;

class StoreUserController extends Controller
{
    private $storeUser;
    private $store;
    private $user;
    public function __construct(StoreUserInterface  $storeUser, StoreInterface $store,UserRepositoryInterface $user)
    {
        $this->storeUser = $storeUser;
        $this->store = $store;
        $this->user = $user;
    }
    public function index()
    {
        $storeUsers = $this->storeUser->index();
        return view('store::store-user.index', compact('storeUsers'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        Gate::authorize('hasCreatePermission');
        $store = $this->store->index();
        $user = $this->user->index();
        return view('store::store-user.create', compact('store', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(CreateStoreUserRequest $request)
    {
        Gate::authorize('hasCreatePermission');
//        return $request;
       $storeUser = $this->storeUser->store($request);
       return redirect()->route('storeuser.index')->with('Success', 'Stored has been Sucessfull');
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('store::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        Gate::authorize('hasEditPermission');
        $stores = $this->store->index();
        $users = $this->user->index();
        $storeUsers = $this->storeUser->edit($id);
        $suser = StoreUser::where('id',$id)->first();
        $stype = Store::where('store_type', $suser->store_type)->where('id', $suser->store_id)->first();

        return view('store::store-user.edit', compact( 'stores', 'users','storeUsers', 'stype'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(UpdateStoreUserRequest $request, $id)
    {
        Gate::authorize('hasCreatePermission');
//        return $request;
        $this->storeUser->update($request, $id);
        return redirect()->route('storeuser.index')->with('success','Store has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        Gate::authorize('hasDeletePermission');
        $this->storeUser->destroy($id);
        return redirect()->route('storeuser.index')->with('success','Store status has been changed successfully');
    }

    public function get_type(Request $request)
    {
        $type = Store::where('store_type', $request->input('type'))
            ->where('status',1)->get();
        return response()->json(['data' => $type]);
    }

}

Modules/Store/Resources/views/store-user/create.blade.php
@extends('dboard.index')

@section('title','Create New Store User Form')

@section('dboard_content')
    <div class="tile">
        <div class="tile-body">
            <!-- title -->
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h2 class="title-heading">Create New Store User</h2>
                </div>
                <div class="col-md-6 text-md-right">
                    <a class="btn index-btn" href="{{route('storeuser.index')}}">Back</a>
                </div>
            </div><!-- end.row -->
            <hr>

            <!-- body -->
            <form method="POST" action="{{ route('storeuser.store') }}" >
            @csrf
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleSelect1">Type</label>
                        <select class="form-control @error('store_type') is-invalid @enderror" name="store_type" onchange="getData(this)">
                            <option selected="true" disabled="disabled">Select Type</option>
                            <option value="hub">Hub</option>
                            <option value="store">Store</option>
                        </select>
                        @error('store_type')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div><!-- end.form-group -->

                    

                    @if(isset($user))
                        <div class="form-group">
                            <label for="exampleSelect1">User</label>
                            <select class="form-control @error('user_id') is-invalid @enderror" name="user_id" id="exampleSelect1" value="{{ old('user_id') }}">
                                <option selected="true" disabled="disabled">Select User</option>
                                @foreach($user as $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach
                            </select>
                        </div><!-- end.form-group -->
                    @endif

                    
                </div><!-- end.col-md-6 -->

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="exampleSelect1">Store / Hub</label>
                        <select class="select2 form-control @error('name') is-invalid @enderror" name="store_id" id="selectedType">
                            <option selected="true" disabled="disabled">Select Store / Hub</option>
                        </select>
                        @error('store_id')
                        <div class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div><!-- end.form-group -->

                    <div class="form-group">
                        @include('store::shares.status')
                  </div><!-- end.form-group -->
                </div><!-- end.col-md-6 -->
            </div><!-- end.row -->
            <hr>

            <div class="row text-right">
                <div class="col-md-12">
                    <button class="btn create-btn" type="submit">Submit</button>
                </div><!-- end.col-md-12 -->
            </div><!-- end.row -->
        </form>
    </div><!-- end.tile-body -->
</div><!-- end.tile -->

@endsection


@push('post_scripts')
    <!-- select2 -->
    <script type="text/javascript" src="{{asset('js/select2.min.js')}}"></script>
    <!-- select2 configuration -->
    <script>
        $(document).ready(function (){
            $(".select2").select2({ width: '100%' });
        });
    </script>

    <script>
        function getData(type){
            var value = type.value;
            var selectType = document.getElementById('selectedType');
            selectType.innerHTML = "";
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: "{{ route('g_type') }}",
                method: 'get',
                data: {
                    type: value
                },
                success: function(result) {
                  let dummySelectOption = document.createElement('option');
                  dummySelectOption.value = "Select Store/Hub";
                  dummySelectOption.innerHTML = "Select Store/Hub";
                  selectType.append(dummySelectOption);
                    for (var i=0; i<result.data.length; i++){
                        opt = document.createElement('option');
                        opt.value = result.data[i].id;
                        opt.innerHTML = result.data[i].name;
                        selectType.appendChild(opt);
                        /*html =  '<option value="'+result.data[i].id+'">'+result.data[i].name+'</option>'
                        selectType.add(html);*/
                    }
                }
            });
        }
    </script>
@endpush

Modules/Store/Resources/views/store-user/edit.blade.php
@extends('dboard.index')

@section('title','Edit New Store Form')

@section('dboard_content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">
                    <!-- title -->
                    <div class="row">
                        <div class="col-md-6">
                            <h2 class="title-heading">Edit New Store</h2>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="btn index-btn" href="{{route('storeuser.index')}}">Back</a>
                        </div><!-- end.col-md-6 -->
                    </div><!-- end.row -->
                    <hr>

                    <!-- form -->
                    <form method="POST" action="{{route('storeuser.update', $storeUsers->id)}}">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleSelect1">Select Type</label>
                                    <select class="form-control @error('store_type') is-invalid @enderror" name="store_type" onchange="getData(this)">
                                        <option selected="true" disabled="disabled">{{ $stype->store_type }}</option>
                                        <option value="hub">Hub</option>
                                        <option value="store">Store</option>
                                    </select>
                                    @error('store_type')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div><!-- end.form-group -->
                            </div><!-- end.col-md-4 -->

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleSelect1">Select Store / Hub</label>
                                    <select class="select2 form-control @error('name') is-invalid @enderror" name="store_id" id="selectedType">
                                        <option selected="true" disabled="disabled">{{ $stype->name }}</option>
                                    </select>
                                    @error('store_id')
                                    <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
                                </div><!-- end.form-group -->
                            </div><!-- end.col-md-4 -->

                            <div class="col-md-4">
                                @if(isset($users))
                                    <div class="form-group">
                                        <label for="exampleSelect1">Store User</label>
                                        <select class="form-control @error('store_id') is-invalid @enderror" name="user_id" id="exampleSelect1">
                                            @foreach($users as $user)
                                                <option value="{{ $user->id }}" @if($user->id == $storeUsers->user_id) selected @endif> {{ $user->name }}</option>
                                            @endforeach
                                        </select>
                                        @error('store_id')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div><!-- end.form-group -->
                                @endif
                            </div><!-- end.col-md-4 -->
                        </div><!-- end.row -->
                        <hr>

                        <!-- button -->
                        <div class="row text-right">
                            <div class="col-md-12">
                                <button class="btn create-btn" type="submit">Update New Store</button>
                            </div><!-- end.col-md-12 -->
                        </div><!-- end.row -->
                    </form>
                </div><!-- end.tile-body -->
            </div><!-- end.tile -->
        </div><!-- end.col-md-12 -->
    </div><!-- end.row -->
@endsection

@push('post_scripts')
    <!-- select2 -->
    <script type="text/javascript" src="{{asset('js/select2.min.js')}}"></script>
    <!-- select2 configuration -->
    <script>
        $(document).ready(function (){
            $(".select2").select2({ width: '100%' });
        });
    </script>

    <script>
        function getData(type){
            var value = type.value;
            var selectType = document.getElementById('selectedType');
            selectType.innerHTML = "";
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: "{{ route('g_type') }}",
                method: 'get',
                data: {
                    type: value
                },
                success: function(result) {
                  let dummySelectOption = document.createElement('option');
                  dummySelectOption.value = "Select Store/Hub";
                  dummySelectOption.innerHTML = "Select Store/Hub";
                  selectType.append(dummySelectOption); 
                    for (var i=0; i<result.data.length; i++){
                        opt = document.createElement('option');
                        opt.value = result.data[i].id;
                        opt.innerHTML = result.data[i].name;
                        selectType.appendChild(opt);
                        /*html =  '<option value="'+result.data[i].id+'">'+result.data[i].name+'</option>'
                        selectType.add(html);*/
                    }
                }
            });
        }
    </script>
@endpush

Modules/Store/Resources/views/store-user/index.blade.php
@extends('dboard.index')

@section('title','View Store User Interface')

@section('dboard_content')

<div class="row" id="actionModal">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">
        <!-- title -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="title-heading">Store User Details</h2>
          </div>
          @can('hasCreatePermission')
          <div class="col-md-6 text-right">
            <a class="btn create-btn" href="{{route('storeuser.create')}}">Add New Store User</a>
          </div>
          @endcan
        </div><!-- end.row -->
        <hr>

        <!-- table -->
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive">
              <table class="table table-hover table-striped table-bordered" id="StoreTypeTable">
                <thead>
                  <tr>
                    <th>SL</th>
                    <th>Store Type</th>
                    <th>Store Name</th>
                    <th>User Name</th>
                    <th>User Role</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @if(isset($storeUsers))
                  @foreach($storeUsers as $key => $storeUser)
                  <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{$storeUser->store_type}}</td>
                    <td>{{$storeUser->store->name}}</td>
                    <td>{{$storeUser->user->name}}</td>
                    <td>{{$storeUser->user->role}}</td>
                    <td>{{$storeUser->status == 1 ? 'Active' : 'InActive' }}</td>
                    <td>
                      <div class="d-flex justify-content-around align-items-center">
                        @can('hasDeletePermission')
                        <form class="mr-3" id="delete_form{{$storeUser->id}}" method="POST" action="{{ route('storeuser.destroy',$storeUser->id) }}" onclick="return confirm('Are you sure?')">@csrf
                          <input name="_method" type="hidden" value="DELETE">
                          <button class="btn edit-btn" type="submit"><i class="fa fa-refresh"></i></button>
                        </form>
                        @endcan

                        @can('hasEditPermission')
                        <a class="btn edit-btn" href="{{route('storeuser.edit',$storeUser->id)}}"><i class="fa fa-pencil"></i></a>
                        @endcan
                      </div>
                    </td>
                  </tr>
                  @endforeach
                  @endif
                </tbody>
              </table>
            </div><!-- end.table-responsive -->
          </div><!-- end.col-md-12 -->
        </div><!-- end.row -->
      </div><!-- end.tile-body -->
    </div><!-- end.tile -->
  </div><!-- end.col-md-12 -->
</div><!-- end.row -->
@endsection

@push('post_scripts')
<script type="text/javascript" src="{{asset('js/plugins/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/plugins/dataTables.bootstrap.min.js')}}"></script>
<script type="text/javascript">
  $('#StoreTypeTable').DataTable();
</script>
@endpush