Modules/Vendor/Routes/web.php
<?php

use Illuminate\Support\Facades\Route;



   


Route::middleware('auth')->prefix('vendor')->group(function() {
   
    Route::resource('vendor-user', 'VendorUserController')->middleware('hq');
    Route::resource('vendortype', 'VendorTypeController')->middleware('hq');
    Route::resource('vendorgroup', 'VendorGroupController')->middleware('hq');
    Route::resource('vendors', 'VendorController')->middleware('hq');
    Route::resource('profile', 'ProfileController')->middleware('vendor');
    Route::resource('dashboard', 'DashboardController')->middleware('vendor');
    Route::resource('sellrequest', 'SellRequestController')->middleware('vendor');
    Route::resource('vendor-invoice', 'SellRequestController')->middleware('vendor');
   
   
    
    Route::get('/sell-request/edit/{id}','SellRequestController@sellRequestEdit')->name('sell.request.edit')->middleware('vendor');
    Route::get('/sell-request/details/{id}','SellRequestController@sellRequestDetails')->name('sell.request.details')->middleware('vendor');
    Route::post('/sell-request/update/{id}','SellRequestController@sell_request_update')->name('sell.request.update')->middleware('vendor');
    Route::get('/sell-request-status/','SellRequestController@sell_request_status_remove')->name('sell.request.remove')->middleware('vendor');
    Route::get('/sell-remain', 'SellRequestController@sellRemainRequest')->name('sell.request.remain')->middleware('vendor');
    Route::get('/sell-remain-details/{id}', 'SellRequestController@sellRemainDetailRequest')->name('sell.remain.details')->middleware('vendor');
    Route::get('/sell-remain-edit/{id}', 'SellRequestController@sellRemainEditRequest')->name('sell.remain.edit')->middleware('vendor');
    Route::get('invoices', 'InvoiceController@invoice')->name('invoice')->middleware('vendor');
    Route::post('vendor-filter','VendorController@vendor_details')->name('filter.vendor')->middleware('hq');
    Route::get('vendor-list','VendorController@get_all_vendor')->name('vendor.list')->middleware('hq');
    Route::get('get-product-by-type-id','VendorController@getProductByTypeId')->name('product.get.by.type.id');
    Route::get('vendor-profile/{id}', 'VendorProfileController@show')->middleware('hq');
    Route::get('vendor-details/{id}','VendorProfileController@vendor_details')->name('vendor.details')->middleware('hq');
    Route::get('/vendor-purchase-order/{id}','VendorProfileController@vendor_purchase_orders')->name('vendor.purchase.order')->middleware('vendor');
    Route::get('/vendor-purchase-product/{id}','VendorProfileController@vendor_purchase_product')->name('vendor.purchase.product')->middleware('vendor');
    Route::get('/vendor-purchase-payment/{id}','VendorProfileController@vendor_purchase_payment')->name('vendor.purchase.payment')->middleware('vendor');
    Route::get('/vendortype-edit/{id}', 'VendorTypeController@vendor_type_edit')->middleware('hq');
    Route::post('/vendortype-update', 'VendorTypeController@vednorUpdate')->middleware('hq');
    Route::get('/vendorgroup-edit/{id}', 'VendorGroupController@vendor_group_edit')->middleware('hq');
    Route::post('/vendorgroup-update', 'VendorGroupController@vendorUpdate')->middleware('hq');
   
   
    
});

Modules/Vendor/Resources/views/vendor-management/group/create.blade.php
@extends('dboard.index')

@section('title','Create Vendor Type Form')
@push('styles')

<style>
    .required-field::before {
      content: "*";
    color: red;
 }
  </style>
    
@endpush

@section('dboard_content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">

                    <!-- title -->
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <h2 class="title-heading">Create Vendor Group</h2>
                        </div>

                        <div class="col-md-6 text-right">
                            <a class="btn index-btn" href="{{route('vendorgroup.index')}}">Back</a>
                        </div>
                    </div><!-- end.row -->
                    <hr>

                    <!-- body -->
                    <form method="POST" action="{{ route('vendorgroup.store') }}" >
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" >Vendor Group <span class="required-field"></label>
                                    <input class="form-control @error('name') is-invalid @enderror" name="name" type="text" placeholder="Enter vendor type name" value="{{ old('name') }}" required>
                
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    @include('vendor::shares.status')
                                </div>
                            </div>
                        </div><!-- end.row -->
                        <hr>
                
                        <div class="row text-right">
                            <div class="col-md-12">
                                    <button class="btn create-btn" type="submit">Submit</button>
                            </div>
                        </div><!-- end.row -->
                    </form>

                </div><!-- end.tile-body -->
            </div><!-- end.tile -->
        </div><!-- end.col-md-12 -->
    </div><!-- end.row -->
@endsection

Modules/Vendor/Resources/views/vendor-management/group/edit.blade.php
@extends('dboard.index')

@section('title','Vendor Group Type Form')

@section('dboard_content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-body">

                    <!-- title -->
                    <div class="row align-items-center">
                        <div class="col-md-6">
                            <h2 class="title-heading">Vendor Group </h2>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="btn index-btn" href="{{route('vendorgroup.index')}}">Back</a>
                        </div>
                    </div><!-- end.row -->
                    <hr>

                    <!-- body -->
                    <form method="POST" action="{{ route('vendorgroup.update',$vendorGroup->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row justify-content-center">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" >Vendor Group *</label>
                                    <input class="form-control @error('name') is-invalid @enderror" name="name" type="text" @if(isset($vendorGroup))  value="{{ $vendorGroup->name }} @endif" required>
                
                                </div>
                            </div>
                        </div><!-- end.row -->
                        <hr>
                
                        <div class="row justify-content-center text-center align-items-center">
                            <div class="col-md-6 text-center">
                                <button class="btn create-btn" type="submit">Update</button>
                            </div>
                        </div><!-- end.row -->
                    </form>


                </div><!-- end.tile-body -->
            </div><!-- end.tile -->
        </div><!-- end.col-md-12 -->
    </div><!-- end.row -->

    
@endsection

Modules/Vendor/Resources/views/vendor-management/group/index.blade.php
@extends('dboard.index')

@section('title', 'View Vendor Group Interface')

@section('dboard_content')
<div class="row" id="actionModal">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">

        <!-- title -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="title-heading">Vendor Groups </h2>
          </div>

          @can('hasCreatePermission')
          <div class="col-md-6 text-right">
            <a class="btn create-btn" href="{{ route('vendorgroup.create') }}">Add Vendor Group </a>
          </div>
          @endcan
        </div><!-- end.row -->
        <hr>
        <!-- data -->
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive">
              <table class="table table-bordered table-striped table-hover" id="VendorGroupTable">
                <thead>
                  <tr>
                    <th>SL</th>
                    <th>Vendor Group</th>
                    <th>Status</th>
                    <th width="8%">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @if (isset($vendor_groups))
                  @foreach ($vendor_groups as $vendor_group)
                  <tr>
                    <td>{{ $vendor_group->id }}</td>
                    <td>{{ $vendor_group->name }}</td>
                    <td>
                      @if ($vendor_group->status == 1)
                      <span class="badge badge-success m-1 p-2">Active</span>
                      @else
                      <span class="badge badge-danger m-1 p-2">Inactive</span>
                      @endif
                    </td>

                    <td>
                      <div class="d-md-flex justify-content-around align-items-center">
                        @can('hasDeletePermission')
                        <form action="{{ route('vendorgroup.destroy', $vendor_group->id) }}" class="mr-3" method="POST" onclick="return confirm('Are you sure?')">
                          @csrf
                          <input name="_method" type="hidden" value="DELETE">
                          <button class="btn" type="submit"><i class="fa fa-refresh"></i></button>
                        </form>
                        @endcan

                        @can('hasEditPermission')
                        {{-- <a id="edit-button" class="btn edit-btn"
                                                                    data-toggle="modal" data-target="#vendorgroup_add"><i
                                                                        class="fa fa-pencil" aria-hidden="true"
                                                                        data-toggle="tooltip" title="Edit Vendor" onclick="editGroup(this)" data-id="{{$vendor_group->id}}" data-name="{{$vendor_group->name}}"></i></a> --}}
                        <a class="btn edit-btn" href="{{ route('vendorgroup.edit', $vendor_group->id) }}"><i class="fa fa-pencil" aria-hidden="true" data-toggle="tooltip" title="Edit Vendor"></i></a>
                        @endcan
                      </div>
                    </td>
                  </tr>
                  @endforeach
                  @endif
                </tbody>
              </table>
            </div><!-- end.table-responsive -->
          </div><!-- end.col-md-12 -->
        </div><!-- end.row -->
      </div><!-- end.tite-body -->
    </div><!-- end.tile -->
  </div><!-- end.col-md-12 -->
</div><!-- end.row -->
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="vendorgroup_add" tabindex="-1" role="dialog" aria-labelledby="vendorgroup_addLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="vendorgroup_addLabel">Vendor Group Update</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>


      <form method="POST" action="{{ route('vendorgroup.update',1)}}" method="POST">
        @csrf
        @method('PUT')
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <input type="hidden" name="id" id="id">
              <label class="control-label">Vendor Group *</label>
              <input class="form-control @error('name') is-invalid @enderror" name="name" type="text" value="1" required>

            </div>
          </div>
        </div><!-- end.row -->
        <hr>

        <div class="row justify-content-center text-center align-items-center">
          <div class="col-md-6 text-center">
            <button class="btn create-btn" type="submit">Update</button>
          </div>
        </div><!-- end.row -->
      </form>



    </div>

  </div>
</div>

@endsection

@push('post_scripts')
<script>
  function editGroup(e) {
    var id = $(e).data('id');
  }
</script>

<script type="text/javascript" src="{{ asset('js/plugins/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/dataTables.bootstrap.min.js') }}"></script>
<script type="text/javascript">
  $('#VendorGroupTable').DataTable();
</script>

@endpush

Modules/Vendor/Resources/views/vendor-management/group/indexnew.blade.php
@extends('dboard.index')

@section('title','View Vendor Group Interface')

@section('dboard_content')
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">

        <!-- title -->
        <div class="row align-items-center">
          <div class="col-md-6">
            <h2 class="title-heading">Vendor Group</h2>
          </div>

          @can('hasCreatePermission')
          <div class="col-md-6 text-right">
            <a class="btn create-btn" href="{{route('vendorgroup.create')}}">Add Vendor Group</a>
          </div>
          @endcan

        </div><!-- end.row -->
        <hr>

        <div class="row">
          <div class="col-md-12">
            <div class="table-responsive">
              <table class="table table-hover table-bordered" id="VendorTypeTable">
                <thead class="thead">
                  <tr>
                    <th>SN</th>
                    <th>Vendor Group</th>
                    <th>Status</th>
                    <th width="10%">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @if(isset( $vendor_groups))
                  @foreach($vendor_groups as $vendor_group)
                  <tr>
                    <td>{{ $vendor_group->id }}</td>
                    <td>{{$vendor_group->name}}</td>
                    <td>
                      @if( $vendor_group->status == 1 )
                      <span class="badge badge-success m-1 p-2">Active</span>
                      @else
                      <span class="badge badge-danger m-1 p-2">Inactive</span>
                      @endif
                    </td>

                    <td>
                      <div class="d-md-flex justify-content-around align-items-center">
                        @can('hasDeletePermission')
                        <form action="{{route('vendortype.destroy',$vendor_group->id)}}" method="POST" onclick="return confirm('Are you sure?')">
                          @csrf
                          <input name="_method" type="hidden" value="DELETE">
                          <button class="btn edit-btn" title="change status" type="submit"><i class="fa fa-refresh"></i></button>
                        </form>
                        @endcan

                        @can('hasEditPermission')
                        {{-- <a class="btn edit-btn editbtn" href="{{route('vendortype.edit',$vendor_type->id)}}" value="{{$vendor_type->id}}" data-toggle="modal" data-body="{{$vendor_type->name}}" data-target="#myModal"><i class="fa fa-lg fa-pencil"></i></a> --}}
                        <button class="btn edit-btn editbtn" title="edit vendor group" href="#" value="{{$vendor_group->id}}"><i class="fa fa-lg fa-pencil"></i></button>
                        @endcan
                      </div>
                    </td>
                  </tr>
                  @endforeach
                  @endif
                </tbody>
              </table>
            </div><!-- end.table-responsive -->
          </div><!-- end.col-md-12 -->
        </div><!-- end.row -->
      </div><!-- end.tile-body -->
    </div><!-- end.tile -->
  </div><!-- end.col-md-12 -->
</div><!-- end.row -->

<!-- The Modal -->
<div class="modal" id="vendorModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Update Vendor Group</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <form action="{{url('/vendor/vendorgroup-update')}}" method="POST" enctype="multipart/form-data">
        @csrf
        {{-- @method('POST') --}}
        <!-- Modal body -->
        <div class="modal-body">
          <input type="hidden" class="form-control" id="id" name="id">
          <label class="control-label" for="body">Vendor Group <span class="text-danger">*</span></label>
          <input class="form-control" name="name" type="text" id="vendorId" required>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="submit" class="btn create-btn">Update</button>
        </div>
      </form>
    </div>
  </div>
</div>


@endsection

@push('post_scripts')
<script type="text/javascript" src="{{asset('js/plugins/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/plugins/dataTables.bootstrap.min.js')}}"></script>
<script type="text/javascript">
  $('#VendorTypeTable').DataTable();
</script>
<script>
  $(document).ready(function() {


    $(document).on('click', '.editbtn', function() {
      var vendor_group_id = $(this).val();

      var url = "{{ url('/vendor/vendorgroup-edit/')}}/" + vendor_group_id

      //  alert(url);
      $('#vendorModal').modal('show');

      $.ajax({
        type: 'GET',
        url: url,
        // data: "data",
        // dataType: "dataType",
        success: function(response) {
          console.log(response);
          //    var vendorName = response.name;
          //    console.log(vendorName);
          $('#id').val(response.id);
          $('#vendorId').val(response.name);

        }
      });
    });

  })
</script>

@endpush